Repository NillerMedDild/Enigmatica5, pull requests merged in 2020-07, with the labels that each got.

#392 Fixes dupe bug
  config/oreexcavation_groups.json
  scripts/base/unification/pre-unification-removals.zs
Labels: Bug

#402 Added water soil, kelp, IE hemp and Occultism demon fruit to botany pots.
  openloader/data/enigmatica/data/botanypots/recipes/crops/datura.json
  openloader/data/enigmatica/data/botanypots/recipes/crops/hemp.json
  openloader/data/enigmatica/data/botanypots/recipes/crops/kelp.json
  openloader/data/enigmatica/data/botanypots/recipes/soil/water.json
Labels: Enhancement, Status: Awaiting Information

#213 Add Linux instructions to install E5 to README
  .github/README.md
Labels: Enhancement
